### ISSUE TITLE
Release Tags out of order

### ISSUE THREAD

**Issue by adam2k** [nbd-wtf/ln-decodepay#11]
**Issue:**

The release tags are out of order making `v1.11.1` the latest version, although it was released prior to several newer versions.

https://pkg.go.dev/github.com/nbd-wtf/ln-decodepay@v1.11.1?tab=versions

**Suggestion:**

Make a new release tag of `v1.12.0` and increment the `major.minor.patch` changes from that point.

<img width="511" alt="Screenshot 2024-01-16 at 11 27 57 AM" src="https://github.com/nbd-wtf/ln-decodepay/assets/749118/41b99dcf-b1f4-45ba-9653-4de4145368a0">

**Comment by fiatjaf** [comment]
Thank you. I just did that.

**Comment by adam2k** [comment]
@fiatjaf not sure if it'll break things for people, but it looks like the `v1.11.1` tag was removed.  Was that intentional?  It should be an easy fix, but depending on how many people are importing this library their builds will probably break.

**Comment by adam2k** [comment]
> @fiatjaf not sure if it'll break things for people, but it looks like the `v1.11.1` tag was removed. Was that intentional? It should be an easy fix, but depending on how many people are importing this library their builds will probably break.

Correction:  It looks like the `v1.11.1` tag is still hosted here https://pkg.go.dev/github.com/nbd-wtf/ln-decodepay@v1.11.1?tab=versions

Your tag changes _should_ be OK. 👍🏻
