### ISSUE TITLE
tag v1.11.1 not found

### ISSUE THREAD

**Issue by itasli** [nbd-wtf/ln-decodepay#4]
Hey, i was trying to build an application using ln-decodepay as dependency but i got this error :
```
reading github.com/nbd-wtf/ln-decodepay/go.mod at revision v1.11.1: unknown revision v1.11.1
```

Seems like the revision exists on [https://pkg.go.dev/github.com/nbd-wtf/ln-decodepay](https://pkg.go.dev/github.com/nbd-wtf/ln-decodepay) but not on github. 

Can you please create a tag for it

**Comment by fiatjaf** [comment]
I don't know what tag is that anymore. What library are you using that has ln-decodepay as a dependency? It's probably better to upgrade.

**Comment by itasli** [comment]
hey @fiatjaf i'm using https://github.com/believethehype/nostdress, if you check used dependencies you'll see it uses :
`github.com/nbd-wtf/ln-decodepay v1.11.1` the version matches the one on https://pkg.go.dev/github.com/nbd-wtf/ln-decodepay but not visible on the github repository.

When checking the commit history and version update history it seems like both v1.5.1 and v1.11.1 were released on same date (probably the same version) so downgrading dependency on nostdress wouldn't be a problem but i think it would be easier to maintain if both version tags matchs

**Comment by fiatjaf** [comment]
Isn't it better to update the dependency on nostdress? I think it is. I am confused about these numbers.

**Comment by itasli** [comment]
I'll go for it then, but the mismatching version tags will persist...
