### ISSUE TITLE
Publish updated go module

### ISSUE THREAD

**Issue by adam2k** [nbd-wtf/ln-decodepay#7]
To include the recent bug fixes we will need tag and publish a new module.  I'm adding this issue as a reminder to publish.

RE: https://go.dev/doc/modules/publishing#:~:text=%24%20git%20commit%20-m%20%22mymodule%3A%20changes%20for%20v0.1.0%22,modules%20with%20information%20about%20the%20module%20you’re%20publishing.

**Comment by fiatjaf** [comment]
Done.
